spring:
  application:
    name: msv-cobrodar-work
  profiles:
    active: local  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true 
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true


