server:
  port: 8081
  
spring:  rabbitmq:#    host: localhost
    host: 192.168.37.136
    port: 5672
    username: user
    password: unisenha
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://192.168.37.136:5432/postgres
    username: postgres
    password: unisenha
  mail:
    host: smtp.gmail.com
    port: 587
    username: uni.estudo.teste@gmail.com
    password: qqckukpgaprocmxm
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true