server:
  port: 8080
  
spring:  rabbitmq:    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
  datasource:
    url: jdbc:postgresql://${POSTGRE_URL}:${POSTGRE_PORT}/${POSTGRE_DATABASE}
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASS}