server:
  port: 8081
  
spring:  rabbitmq:    host: localhost
    port: 5672
    username: user
    password: unisenha
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: unisenha