create table LOG_BOLETO ( 
	ID SERIAL not null constraint PK_COD_LOG_BOELTO primary key,
	DT_ENVIADO DATE not NULL,
	NUMERO_BOLETO VARCHAR(100),
	ID_PEDIDO INTEGER,
	FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID)

)
	